### PR TITLE
Honor new environment variables, with tests.

### LINKED ISSUE #48: Drupal Finder does not find root when composer.json is not in root but in a root-subfolder
We have inherited a structure similar to:
```
/app (project root)
├── public
│   ├── drupal
|   |   ├── core
|   |   ├── autoload.php = <?php return require __DIR__ . '/../../thunder/vendor/autoload.php'; ?>
|   |   ├── index.php
|   |   └── ...
│   └── others
└── thunder
    ├── composer.json
    ├── composer.lock
    ├── sync
    └── vendor
```

This worked well using drush 8, but bootstrapping failed after upgrading to drush:

```
[bootstrap] Starting bootstrap to site [0.56 sec, 10.72 MB]
In BootstrapHook.php line 33:
  [Exception]
  Bootstrap failed. Run your command with -vvv for more information.
```

It seems that the problem lies in `DrupalFinder::isValidRoot($path)`. Hardcoding the drupal-/composer-root and vendor dir there (like below) worked:
```
$this->drupalRoot = '/app/thunder/../public/drupal';
$this->composerRoot = '/app/thunder';
$this->vendorDir = '/app/thunder/vendor';
return $this->drupalRoot && $this->composerRoot && $this->vendorDir;
```

So the problem seems to be that the assumptions on the project structure are not universal. I am not sure if this needs to be addressed in drupal-finder or in drush itself by environment variables or drush options similar to [--drupal-root](https://github.com/mglaman/drupal-check/pull/98/commits) in mglaman/drupal-check.

A workaround could be to add a (minimal) composer.json file to /app/public/drupal with following content:
```
{
    "description": "Workaround for drupal-finder to find drupal-, composer-root and vendor dir, see https://github.com/webflo/drupal-finder/issues/48",
    "extra": {
        "installer-paths": {
            "core": ["type:drupal-core"]
        }
    }
}
```

Would this be valid or may this introduce problems somewhere else?

### PR DESCRIPTION
**Pull request by lpeabody**
# Changes

- Provide certain named environment variables whose values are the paths to the appropriate directory. If the environment variables are present, and their value represents a valid path to a directory, then its value is returned in the getter function regardless of the value assigned to the respective path data property.

The environment variables which can be specified are:

- `DRUPAL_FINDER_DRUPAL_ROOT`
- `DRUPAL_FINDER_COMPOSER_ROOT`
- `DRUPAL_FINDER_VENDOR_DIR`

As an example, if you have the environment variable `DRUPAL_FINDER_DRUPAL_ROOT=/var/www/web`, then `DrupalFinder::getDrupalRoot` will return `/var/www/web`, assuming that this is actually a valid directory.

## BC breaks

**`DrupalFinder::locateRoot` now returns true if the Drupal root is known, regardless of whether or not vendor or Composer roots are known**

If the Drupal root is known, but the Composer and vendor directories cannot be found or are otherwise unknown, then this function will still return `true`.

Effects the following use cases:

- Code that checked the result of `DrupalFinder::locateRoot` and subsequently went on to use `DrupalFinder::getComposerRoot` or `DrupalFinder::getVendorDir` without validating the results of each retrieval. If either the Composer root or vendor directory could not be discovered, and no environment variables were specified providing their values, then previous code which assumed a string would be present will now instead get a value of `false`.

Fixes #48

### CODE REVIEW

**Comment by weitzman** [comment]
Looks great to me. My inclination is that specifying these vars should simply bypass the existing detection logic, and not simply be a fallback.

**Comment by lpeabody** [comment]
@weitzman makes sense to me. If you're setting something explicitly its usually because you want to use that information. However, @webflo  seemed to indicate he preferred for the regular build logic to run first over in #48, which is why I implemented it the way I did.

@webflo what are your thoughts?

**Comment by lpeabody** [comment]
For the sake of consideration and example, I went ahead and made the change where Drupal Finder always uses the environment variable path values if they are set.

**Comment by weitzman** [comment]
In Drush's case, we dont care about vendor dir and only in pm:security command care about composer dir. So, I'd prefer not to pass values for those when the user has passed a --root. So, I propose we skip validity checks when the env variables are set. Thoughts?

**Comment by lpeabody** [comment]
@weitzman Made some more changes which should be helpful. I tried to update the functionality such that:

- All previous functionality is maintained.
- You are free to set any number of environment variables, and retrieve their values with the associated getter functions. A set environment variable will **_ALWAYS_** override the value of the associated path property.

I reorganized the code quite a bit. The updates effectively make the following changes:

- There is now a distinction between **discovered** and **known**:
    - A path is **discovered** if it has been located on the file system via search.
    - A path is **known** if it has been discovered OR if it has an environment variable that contains a valid path to a directory.
    - Therefore a path can be known but not discovered, and a discovered path is always known.
- `DrupalFinder::locateRoot` now returns `true` if the Drupal root is known, regardless of whether or not the Composer root or vendor directory locations are known. This is _technically_ a BC break (see PR description for details).
- The path properties are `false` until they have been discovered.
- `DrupalFinder::locateRoot` was deprecated in favor of constructor initialization. I added a protected member function `DrupalFinder::discoverRoots` which effectively does the same thing as `DrupalFinder::locateRoot`, but it is more appropriately named and non-public, thereby forcing constructor initialization. This was needed to make intents much clearer.

Once `DrupalFinder::locateRoot` has been removed in v2, you are left with the following public member functions:

- `DrupalFinder::__construct`
    - Initializes and discovers the paths to the Drupal root, Composer root, and vendor directory.
- `DrupalFinder::getDrupalRoot`
    - Returns the Drupal root if it is known, false otherwise.
- `DrupalFinder::getComposerRoot`
    - Returns the Composer root if it is known, false otherwise.
- `DrupalFinder::getVendorDir`
    - Returns the vendor directory path if it is known, false otherwise.

In the meantime, `DrupalFinder::locateRoot` does the exact same thing that the constructor does and can still be used publicly.

**Review by weitzman — APPROVED** [review]
This looks terrific to me. We could merge as is, or remove locateRoot() and tag  a new major version. Up to @webflo.

**Comment by lpeabody** [comment]
As an anecdote, I went ahead and tested this on one of my Drupal projects deployed in a highly stripped-down artifact in a Docker container. I had previously included a hacked composer.json file that permitted DrupalFinder to work.

I went ahead and removed the hacked composer.json from the artifact, and _only_ added the environment variable `DRUPAL_FINDER_DRUPAL_ROOT=/var/www/web`. Drush ran beautifully :+1: .

**Comment by webflo** [comment]
Thanks @lpeabody for your work. I will review it soon.

**Comment by webflo** [comment]
Thanks @lpeabody! I fixed the type-hint after the update to phpunit 8 in master.

**Comment by webflo** [comment]
LGTM!

**Comment by weitzman** [comment]
Thanks @webflo. Any chance for a release (beta or full)? I made a Drush PR that uses this new code https://github.com/drush-ops/drush/pull/4676

**Pull request merged**
